version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./tmp/database:/var/lib/postgresql/data