service: todo-example-api-node
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DB_HOST: serverless-series-db.clde4adlxv9d.us-east-1.rds.amazonaws.com
    DB_USER: serverlessseries
    DB_PASS: Password123
    DB_PORT: 5432
    DB_NAME: node_sls

functions:
  hello:
    handler: handler.ping
